steps:
- name: "gcr.io/cloud-builders/yarn"
  args: [""]
- name: "gcr.io/cloud-builders/yarn"
  args: ["build"]
  env:
  - 'NODE_ENV=production'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--no-promote"]
timeout: "1600s"
