steps:
- name: "gcr.io/cloud-builders/yarn"
  args: [""]
- name: "gcr.io/cloud-builders/yarn"
  args: ["build"]
  env:
  - 'NODE_ENV=production'
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: bash
  args:
    - -c
    - |
      version=`echo $TAG_NAME | sed 's/\./-/g'`
      gcloud app deploy --no-promote --version=$version
timeout: "1600s"
